server:
  port: 8001

spring:
  thymeleaf:
    prefix: classpath:./templates/
    suffix: .html
    cache: false
    encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true

mybatis:
  type-aliases-package: com.example.springboot.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
